// <auto-generated />
using System;
using AppServiceAndTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServiceAndTravel.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260522142450_seed permisos")]
    partial class seedPermisos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppServiceAndTravel.Models.ApplicationUser", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("avatar")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("confirmada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("crypt")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("fechaBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaCambioClave")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fechaExpiracionToken")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("hast")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("refreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("restaurada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("token")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            activo = true,
                            admin = true,
                            cargo = "Administrador",
                            confirmada = true,
                            correo = "admin@correo.com",
                            crypt = true,
                            fechaCambioClave = new DateTime(2026, 8, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5553),
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5552),
                            fechaModificacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5554),
                            hast = true,
                            nombreCompleto = "Administrador",
                            password = "admin",
                            restaurada = false,
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitCedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Conductor", b =>
                {
                    b.Property<int>("idConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConductor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CategoriaLicencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EmpresaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoLicencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitEmpresa")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ObservacionesExterno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("TarifaExterna")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idConductor");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("NumeroLicencia")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ConfigNotificaciones", b =>
                {
                    b.Property<string>("smtpServer")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("requiereSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("requiereTSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("smtpPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("smtpPort")
                        .HasColumnType("longtext");

                    b.Property<string>("smtpUserName")
                        .HasColumnType("longtext");

                    b.HasKey("smtpServer");

                    b.ToTable("ConfiguracionNotificaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ConfiguracionGeneral", b =>
                {
                    b.Property<int>("idConfiguracionGeneral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConfiguracionGeneral"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ColorAcento")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorTexto")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("DiasAlertaVencimiento")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Eslogan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FormatoFecha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("JwtExpiracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("JwtSecret")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ModificadoPorId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NitEmpresa")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreRemitente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("NotificarPorWhatsApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificarPorcorreo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RutaFavicon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RutaLogo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeparadorDecimal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SeparadorMiles")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SimboloMoneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("correoRemitente")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idConfiguracionGeneral");

                    b.ToTable("ConfiguracionGeneral");

                    b.HasData(
                        new
                        {
                            idConfiguracionGeneral = 1,
                            ColorAcento = "#16a34a",
                            ColorFondo = "#f0f4f8",
                            ColorPrimario = "#1a6fc4",
                            ColorSecundario = "#0f1c2e",
                            ColorTexto = "#1e293b",
                            DiasAlertaVencimiento = 30,
                            FormatoFecha = "dd/MM/yyyy",
                            Idioma = "es-CO",
                            JwtExpiracionMinutos = 60,
                            Moneda = "COP",
                            NombreEmpresa = "Service And Travel",
                            NotificarPorWhatsApp = true,
                            NotificarPorcorreo = true,
                            Pais = "Colombia",
                            SeparadorDecimal = ",",
                            SeparadorMiles = ".",
                            SimboloMoneda = "$",
                            UltimaModificacion = new DateTime(2026, 5, 22, 9, 24, 50, 180, DateTimeKind.Local).AddTicks(8160),
                            ZonaHoraria = "America/Bogota"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCarga")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaServicioRequerido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionesAprobacion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ObservacionesRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UsuarioAprobadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorAprobado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorCotizado")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioAprobadorId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.FormatosCorreos", b =>
                {
                    b.Property<int>("idCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCorreo"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("abreviatura")
                        .HasColumnType("longtext");

                    b.Property<string>("mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .HasColumnType("longtext");

                    b.HasKey("idCorreo");

                    b.ToTable("FormatosCorreos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistLogin", b =>
                {
                    b.Property<int?>("idHist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idHist"));

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("inSesion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("mensaje")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("userName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("valido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idHist");

                    b.ToTable("HistLogin");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistRefreshToken", b =>
                {
                    b.Property<int>("IdHistRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHistRefreshToken"));

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioNavigationidUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdHistRefreshToken");

                    b.HasIndex("idUsuarioNavigationidUsuario");

                    b.ToTable("HistRefreshToken");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Notificacion", b =>
                {
                    b.Property<int?>("idNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idNotificacion"));

                    b.Property<string>("categoriaNotificacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("leido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("mensjae")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("titulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idNotificacion");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Permisos", b =>
                {
                    b.Property<int>("idProceso")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<bool>("crea")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("edita")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("elimina")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("lectura")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idProceso", "idRol");

                    b.HasIndex("idRol");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            idProceso = 1,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5399),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 2,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5404),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 3,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5405),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 4,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5406),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 5,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5408),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 6,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5409),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 7,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5410),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 8,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5411),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 9,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5412),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 10,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5413),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 11,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5414),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 12,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5415),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 13,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5416),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 14,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5417),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 15,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5418),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 16,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5419),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 17,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5420),
                            lectura = true
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.Property<int>("idProceso")
                        .HasColumnType("int");

                    b.Property<string>("area")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("controlador")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("icono")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("idProcesoPadre")
                        .HasColumnType("int");

                    b.Property<string>("proceso")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("url")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("idProceso");

                    b.HasIndex("idProcesoPadre");

                    b.ToTable("Procesos");

                    b.HasData(
                        new
                        {
                            idProceso = 1,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5016),
                            icono = "fa-gear",
                            proceso = "Configuracion"
                        },
                        new
                        {
                            idProceso = 2,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5023),
                            icono = "fa-shop",
                            proceso = "Productos"
                        },
                        new
                        {
                            idProceso = 3,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5025),
                            icono = "fa-user",
                            idProcesoPadre = 1,
                            proceso = "Usuarios"
                        },
                        new
                        {
                            idProceso = 4,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5027),
                            idProcesoPadre = 3,
                            proceso = "Users",
                            url = "AdminManagement"
                        },
                        new
                        {
                            idProceso = 5,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5029),
                            idProcesoPadre = 1,
                            proceso = "Apariencia",
                            url = "Appearance"
                        },
                        new
                        {
                            idProceso = 6,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5030),
                            idProcesoPadre = 1,
                            proceso = "Base de datos",
                            url = "DatabaseConnections"
                        },
                        new
                        {
                            idProceso = 7,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5032),
                            idProcesoPadre = 2,
                            proceso = "Gestion de productos",
                            url = "ProductsManagement"
                        },
                        new
                        {
                            idProceso = 8,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5033),
                            idProcesoPadre = 3,
                            proceso = "notification",
                            url = "RolPermissions"
                        },
                        new
                        {
                            idProceso = 9,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5035),
                            idProcesoPadre = 1,
                            proceso = "Provedores",
                            url = "SupplierManagement"
                        },
                        new
                        {
                            idProceso = 10,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5036),
                            idProcesoPadre = 1,
                            proceso = "Sistema",
                            url = "SystemConfiguration"
                        },
                        new
                        {
                            idProceso = 11,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5038),
                            icono = "fa-store",
                            proceso = "Ventas",
                            url = "Ventas"
                        },
                        new
                        {
                            idProceso = 12,
                            controlador = "Home",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5039),
                            proceso = "Dashboard",
                            url = "index"
                        },
                        new
                        {
                            idProceso = 13,
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5040),
                            icono = "fa-cart-shopping",
                            idProcesoPadre = 11,
                            proceso = "Venta",
                            url = "Sales"
                        },
                        new
                        {
                            idProceso = 14,
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5042),
                            icono = "fa-shop",
                            proceso = "Productos",
                            url = "Products"
                        },
                        new
                        {
                            idProceso = 15,
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5043),
                            idProcesoPadre = 14,
                            proceso = "Gestion de Productos",
                            url = "ProductsManagement"
                        },
                        new
                        {
                            idProceso = 16,
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5045),
                            idProcesoPadre = 14,
                            proceso = "Pedidos",
                            url = "Orders"
                        },
                        new
                        {
                            idProceso = 17,
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5046),
                            idProcesoPadre = 14,
                            proceso = "Gestion de Pedidos",
                            url = "OrdersManagement"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ProveedorExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitCedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TarifaBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProveedoresExternos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Proveedores", b =>
                {
                    b.Property<int>("idProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idProveedor"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Roles", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRol"));

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            idRol = 1,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5244),
                            fechaModificacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5244),
                            nombre = "Administrador"
                        },
                        new
                        {
                            idRol = 2,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5247),
                            fechaModificacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5247),
                            nombre = "Usuarios"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.RolesUsuarios", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idUser")
                        .HasColumnType("int");

                    b.HasKey("idUsuario", "idRol");

                    b.HasIndex("idRol");

                    b.ToTable("RolesUsuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            idRol = 1,
                            fechaCreacion = new DateTime(2026, 5, 22, 14, 24, 50, 178, DateTimeKind.Utc).AddTicks(5324)
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConductorExternoCedula")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ConductorExternoNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ConductorExternoTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoExterno")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaServicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NotificacionWhatsAppEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificacioncorreoEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("ProveedorExternoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoServicio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("UsaRecursoExterno")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<string>("VehiculoExternoDescripcion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("VehiculoExternoPlaca")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("CotizacionId")
                        .IsUnique();

                    b.HasIndex("ProveedorExternoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ValidacionVehiculo", b =>
                {
                    b.Property<int>("idValidacionVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idValidacionVehiculo"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaValidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LicenciaConductorVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SOATVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SeguroVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TecnoVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("idServicio")
                        .HasColumnType("int");

                    b.Property<int>("idVehiculo")
                        .HasColumnType("int");

                    b.HasKey("idValidacionVehiculo");

                    b.HasIndex("idVehiculo");

                    b.ToTable("ValidacionesVehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Vehiculo", b =>
                {
                    b.Property<int>("idVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("CapacidadCarga")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaVencimientoSOAT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoSeguro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoTecnoMecanica")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("PropietarioCedula")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PropietarioNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PropietarioTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Propietariocorreo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaSOAT")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaSeguro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaTecnoMecanica")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TarifaExterna")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idVehiculo");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizacion", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Cliente", "Cliente")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioAprobador");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistRefreshToken", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "idUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("idUsuarioNavigationidUsuario");

                    b.Navigation("idUsuarioNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Permisos", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Procesos", "proceso")
                        .WithMany("Permisos")
                        .HasForeignKey("idProceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.Roles", "rol")
                        .WithMany("Permisos")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("proceso");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Procesos", "idProcesoPadreNavigation")
                        .WithMany("inverseidProcesoPadreNavigation")
                        .HasForeignKey("idProcesoPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("idProcesoPadreNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.RolesUsuarios", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Roles", "Rol")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "Usuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Servicio", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Conductor", "Conductor")
                        .WithMany("Servicios")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.Cotizacion", "Cotizacion")
                        .WithOne("Servicio")
                        .HasForeignKey("AppServiceAndTravel.Models.Servicio", "CotizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ProveedorExterno", "ProveedorExterno")
                        .WithMany()
                        .HasForeignKey("ProveedorExternoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppServiceAndTravel.Models.Vehiculo", "Vehiculo")
                        .WithMany("Servicios")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Cotizacion");

                    b.Navigation("ProveedorExterno");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ValidacionVehiculo", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("idVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ApplicationUser", b =>
                {
                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cliente", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Conductor", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizacion", b =>
                {
                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("inverseidProcesoPadreNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Roles", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Vehiculo", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
