// <auto-generated />
using System;
using AppServiceAndTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServiceAndTravel.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260526181354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppServiceAndTravel.Models.ActividadSistema", b =>
                {
                    b.Property<int>("idActividadSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idActividadSistema"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Entidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("idTipoActividadSistema")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idActividadSistema");

                    b.HasIndex("idTipoActividadSistema");

                    b.HasIndex("idUsuario");

                    b.ToTable("ActividadesSistema");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ApplicationUser", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("avatar")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("confirmada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("crypt")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("fechaBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaCambioClave")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fechaExpiracionToken")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("hast")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("refreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("restaurada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("token")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            activo = true,
                            admin = true,
                            cargo = "Administrador",
                            confirmada = true,
                            correo = "admin@correo.com",
                            crypt = true,
                            fechaCambioClave = new DateTime(2026, 8, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4952),
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4951),
                            fechaModificacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4953),
                            hast = true,
                            nombreCompleto = "Administrador",
                            password = "admin",
                            restaurada = false,
                            ultimoAcceso = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4932),
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Clientes", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitCedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Conductores", b =>
                {
                    b.Property<int>("idConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConductor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CategoriaLicencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EmpresaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoLicencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitEmpresa")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ObservacionesExterno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("TarifaExterna")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idConductor");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("NumeroLicencia")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ConfigNotificaciones", b =>
                {
                    b.Property<int>("idConfigNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConfigNotificacion"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("NombreRemitente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProveedorWhatsApp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WhatsAppApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("WhatsAppApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("WhatsAppFechaValidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WhatsAppNumeroEmpresa")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("WhatsAppValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("correoRemitente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("requiereSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("requiereTSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("smtpPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("smtpPort")
                        .HasColumnType("int");

                    b.Property<string>("smtpServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("smtpUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idConfigNotificacion");

                    b.ToTable("ConfiguracionNotificaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ConfiguracionGeneral", b =>
                {
                    b.Property<int>("idConfiguracionGeneral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConfiguracionGeneral"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ColorAcento")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorAdvertencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorPeligro")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColorTexto")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DiasAlertaVencimiento")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Eslogan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FormatoFecha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FuenteSistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("JwtAudience")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("JwtExpirationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("JwtIssuer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("JwtSecretKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ModificadoPorId")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NitEmpresa")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("NotificarPorWhatsApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificarPorcorreo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RutaFavicon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RutaLogo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeparadorDecimal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SeparadorMiles")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SimboloMoneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TamanoFuenteBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TemaSeleccionado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idConfiguracionGeneral");

                    b.ToTable("ConfiguracionGeneral");

                    b.HasData(
                        new
                        {
                            idConfiguracionGeneral = 1,
                            ColorAcento = "#16a34a",
                            ColorAdvertencia = "#f59e0b",
                            ColorFondo = "#f0f4f8",
                            ColorPeligro = "#dc2626",
                            ColorPrimario = "#0080ff",
                            ColorSecundario = "#52e5ff",
                            ColorTexto = "#1e293b",
                            DiasAlertaVencimiento = 30,
                            FormatoFecha = "dd/MM/yyyy",
                            FuenteSistema = "Inter",
                            Idioma = "es-CO",
                            JwtAudience = "AppServiceAndTravelApp",
                            JwtExpirationMinutes = 60,
                            JwtIssuer = "AppServiceAndTravelAPI",
                            JwtSecretKey = "EstaEsUnaLlaveSecretaSeguraYBienLarga",
                            Moneda = "COP",
                            NombreEmpresa = "Service And Travel",
                            NotificarPorWhatsApp = true,
                            NotificarPorcorreo = true,
                            Pais = "Colombia",
                            SeparadorDecimal = ",",
                            SeparadorMiles = ".",
                            SimboloMoneda = "$",
                            TamanoFuenteBase = "14px",
                            TemaSeleccionado = "Azul corporativo",
                            UltimaModificacion = new DateTime(2026, 5, 26, 13, 13, 53, 752, DateTimeKind.Local).AddTicks(2490),
                            ZonaHoraria = "America/Bogota"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizaciones", b =>
                {
                    b.Property<int>("idCotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCotizacion"));

                    b.Property<string>("DescripcionCarga")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaServicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionesAprobacion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ObservacionesRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("ValorAprobado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorCotizado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioAprobador")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioCreador")
                        .HasColumnType("int");

                    b.HasKey("idCotizacion");

                    b.HasIndex("idCliente");

                    b.HasIndex("idUsuarioAprobador");

                    b.HasIndex("idUsuarioCreador");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.FormatosCorreos", b =>
                {
                    b.Property<int>("idCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCorreo"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("abreviatura")
                        .HasColumnType("longtext");

                    b.Property<string>("mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .HasColumnType("longtext");

                    b.HasKey("idCorreo");

                    b.ToTable("FormatosCorreos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistLogin", b =>
                {
                    b.Property<int?>("idHist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idHist"));

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("inSesion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("mensaje")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("userName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("valido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idHist");

                    b.ToTable("HistLogin");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistRefreshToken", b =>
                {
                    b.Property<int>("IdHistRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHistRefreshToken"));

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioNavigationidUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdHistRefreshToken");

                    b.HasIndex("idUsuarioNavigationidUsuario");

                    b.ToTable("HistRefreshToken");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.LogSistema", b =>
                {
                    b.Property<int>("idLogSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idLogSistema"));

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetodoHttp")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idLogSistema");

                    b.HasIndex("idUsuario");

                    b.ToTable("LogsSistema");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Notificaciones", b =>
                {
                    b.Property<int?>("idNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idNotificacion"));

                    b.Property<string>("categoriaNotificacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("leido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("mensjae")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("titulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idNotificacion");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Permisos", b =>
                {
                    b.Property<int>("idProceso")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<bool>("crea")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("edita")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("elimina")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("lectura")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idProceso", "idRol");

                    b.HasIndex("idRol");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            idProceso = 1,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4702),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 2,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4709),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 3,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4762),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 4,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4764),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 5,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4765),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 6,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4767),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 7,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4768),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 8,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4769),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 9,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4770),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 10,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4771),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 11,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4772),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 12,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4773),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 13,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4775),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 14,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4776),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 15,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4777),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 16,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4778),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 17,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4779),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 18,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4780),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 19,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4781),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 20,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4782),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 21,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4783),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 22,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4784),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 23,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4786),
                            lectura = true
                        },
                        new
                        {
                            idProceso = 24,
                            idRol = 1,
                            crea = false,
                            edita = true,
                            elimina = true,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4787),
                            lectura = true
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.Property<int>("idProceso")
                        .HasColumnType("int");

                    b.Property<string>("area")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("controlador")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("icono")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("idProcesoPadre")
                        .HasColumnType("int");

                    b.Property<string>("proceso")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("url")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("idProceso");

                    b.HasIndex("idProcesoPadre");

                    b.ToTable("Procesos");

                    b.HasData(
                        new
                        {
                            idProceso = 1,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4129),
                            icono = "fa-user-shield",
                            proceso = "Seguridad"
                        },
                        new
                        {
                            idProceso = 2,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4135),
                            icono = "fa-gear",
                            idProcesoPadre = 1,
                            proceso = "Configuracion"
                        },
                        new
                        {
                            idProceso = 3,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4137),
                            idProcesoPadre = 2,
                            proceso = "Configuracion General",
                            url = "ConfiguracionGeneral"
                        },
                        new
                        {
                            idProceso = 4,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4139),
                            idProcesoPadre = 2,
                            proceso = "Usuarios",
                            url = "Usuarios"
                        },
                        new
                        {
                            idProceso = 5,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4140),
                            idProcesoPadre = 2,
                            proceso = "Roles",
                            url = "Roles"
                        },
                        new
                        {
                            idProceso = 6,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4142),
                            idProcesoPadre = 2,
                            proceso = "Permisos",
                            url = "Permisos"
                        },
                        new
                        {
                            idProceso = 7,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4144),
                            icono = "fa-users-rectangle",
                            proceso = "Proveedores"
                        },
                        new
                        {
                            idProceso = 8,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4145),
                            idProcesoPadre = 7,
                            proceso = "Listado de Proveedores",
                            url = "Proveedores"
                        },
                        new
                        {
                            idProceso = 9,
                            area = "Admin",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4146),
                            idProcesoPadre = 7,
                            proceso = "Nuevo Proveedor",
                            url = "CrearProveedor"
                        },
                        new
                        {
                            idProceso = 10,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4148),
                            icono = "fa-address-card",
                            proceso = "Conductores"
                        },
                        new
                        {
                            idProceso = 11,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4149),
                            idProcesoPadre = 10,
                            proceso = "Listado de Conductores",
                            url = "Conductores"
                        },
                        new
                        {
                            idProceso = 12,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4151),
                            idProcesoPadre = 10,
                            proceso = "Nuevo Conductor",
                            url = "CrearConductor"
                        },
                        new
                        {
                            idProceso = 13,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4152),
                            icono = "fa-car",
                            proceso = "Vehiculos"
                        },
                        new
                        {
                            idProceso = 14,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4154),
                            idProcesoPadre = 13,
                            proceso = "Listado de Vehiculos",
                            url = "Vehiculos"
                        },
                        new
                        {
                            idProceso = 15,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4155),
                            idProcesoPadre = 13,
                            proceso = "Nuevo Vehiculo",
                            url = "CrearVehiculo"
                        },
                        new
                        {
                            idProceso = 16,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4157),
                            icono = "fa-handshake",
                            proceso = "Cotizaciones"
                        },
                        new
                        {
                            idProceso = 17,
                            area = "Comercial",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4158),
                            idProcesoPadre = 16,
                            proceso = "Historial",
                            url = "Cotizaciones"
                        },
                        new
                        {
                            idProceso = 18,
                            area = "Comercial",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4160),
                            idProcesoPadre = 16,
                            proceso = "Nueva Cotización",
                            url = "CrearCotizacion"
                        },
                        new
                        {
                            idProceso = 19,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4161),
                            icono = "fa-handshake",
                            proceso = "Clientes"
                        },
                        new
                        {
                            idProceso = 20,
                            area = "Comercial",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4163),
                            idProcesoPadre = 19,
                            proceso = "Listado de Clientes",
                            url = "Clientes"
                        },
                        new
                        {
                            idProceso = 21,
                            area = "Comercial",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4164),
                            idProcesoPadre = 19,
                            proceso = "Nuevo Cliente",
                            url = "CrearCliente"
                        },
                        new
                        {
                            idProceso = 22,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4167),
                            icono = "fa-car-side",
                            proceso = "Servicios"
                        },
                        new
                        {
                            idProceso = 23,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4169),
                            idProcesoPadre = 22,
                            proceso = "Historial",
                            url = "Servicios"
                        },
                        new
                        {
                            idProceso = 24,
                            area = "Operaciones",
                            controlador = "App",
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4171),
                            idProcesoPadre = 22,
                            proceso = "Nuevo Servicio",
                            url = "CrearServicio"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Proveedores", b =>
                {
                    b.Property<int>("idProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idProveedor"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ProveedoresExternos", b =>
                {
                    b.Property<int>("IdProveedorExterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedorExterno"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NitCedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TarifaBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdProveedorExterno");

                    b.ToTable("ProveedoresExternos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Roles", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRol"));

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("idRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            idRol = 1,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4431),
                            fechaModificacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4432),
                            nombre = "Administrador"
                        },
                        new
                        {
                            idRol = 2,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4436),
                            fechaModificacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4437),
                            nombre = "Usuarios"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.RolesUsuarios", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idUser")
                        .HasColumnType("int");

                    b.HasKey("idUsuario", "idRol");

                    b.HasIndex("idRol");

                    b.ToTable("RolesUsuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            idRol = 1,
                            fechaCreacion = new DateTime(2026, 5, 26, 18, 13, 53, 749, DateTimeKind.Utc).AddTicks(4581)
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Servicios", b =>
                {
                    b.Property<int>("idServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idServicio"));

                    b.Property<string>("ConductorExternoCedula")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ConductorExternoNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ConductorExternoTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<decimal?>("CostoExterno")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaServicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NotificacionWhatsAppEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificacioncorreoEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TipoServicio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("UsaRecursoExterno")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VehiculoExternoDescripcion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("VehiculoExternoPlaca")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("idConductor")
                        .HasColumnType("int");

                    b.Property<int>("idCotizacion")
                        .HasColumnType("int");

                    b.Property<int?>("idProveedorExterno")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int>("idVehiculo")
                        .HasColumnType("int");

                    b.HasKey("idServicio");

                    b.HasIndex("idConductor");

                    b.HasIndex("idCotizacion")
                        .IsUnique();

                    b.HasIndex("idProveedorExterno");

                    b.HasIndex("idUsuarioCreador");

                    b.HasIndex("idVehiculo");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.TipoActividadSistema", b =>
                {
                    b.Property<int>("idTipoActividadSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idTipoActividadSistema"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("idTipoActividadSistema");

                    b.ToTable("TiposActividadSistema");

                    b.HasData(
                        new
                        {
                            idTipoActividadSistema = 1,
                            Activo = true,
                            Codigo = "COTIZACION_CREADA",
                            Color = "primary",
                            Icono = "bi-file-earmark-plus",
                            Nombre = "Cotización Creada"
                        },
                        new
                        {
                            idTipoActividadSistema = 2,
                            Activo = true,
                            Codigo = "COTIZACION_EDITADA",
                            Color = "warning",
                            Icono = "bi-pencil-square",
                            Nombre = "Cotización Editada"
                        },
                        new
                        {
                            idTipoActividadSistema = 3,
                            Activo = true,
                            Codigo = "COTIZACION_APROBADA",
                            Color = "success",
                            Icono = "bi-check-circle",
                            Nombre = "Cotización Aprobada"
                        },
                        new
                        {
                            idTipoActividadSistema = 4,
                            Activo = true,
                            Codigo = "COTIZACION_RECHAZADA",
                            Color = "danger",
                            Icono = "bi-x-circle",
                            Nombre = "Cotización Rechazada"
                        },
                        new
                        {
                            idTipoActividadSistema = 5,
                            Activo = true,
                            Codigo = "COTIZACION_CANCELADA",
                            Color = "secondary",
                            Icono = "bi-slash-circle",
                            Nombre = "Cotización Cancelada"
                        },
                        new
                        {
                            idTipoActividadSistema = 6,
                            Activo = true,
                            Codigo = "SERVICIO_CREADO",
                            Color = "primary",
                            Icono = "bi-truck",
                            Nombre = "Servicio Creado"
                        },
                        new
                        {
                            idTipoActividadSistema = 7,
                            Activo = true,
                            Codigo = "SERVICIO_PROGRAMADO",
                            Color = "info",
                            Icono = "bi-calendar-event",
                            Nombre = "Servicio Programado"
                        },
                        new
                        {
                            idTipoActividadSistema = 8,
                            Activo = true,
                            Codigo = "SERVICIO_ASIGNADO",
                            Color = "warning",
                            Icono = "bi-person-check",
                            Nombre = "Servicio Asignado"
                        },
                        new
                        {
                            idTipoActividadSistema = 9,
                            Activo = true,
                            Codigo = "SERVICIO_INICIADO",
                            Color = "primary",
                            Icono = "bi-play-circle",
                            Nombre = "Servicio Iniciado"
                        },
                        new
                        {
                            idTipoActividadSistema = 10,
                            Activo = true,
                            Codigo = "SERVICIO_EN_CURSO",
                            Color = "warning",
                            Icono = "bi-arrow-repeat",
                            Nombre = "Servicio En Curso"
                        },
                        new
                        {
                            idTipoActividadSistema = 11,
                            Activo = true,
                            Codigo = "SERVICIO_FINALIZADO",
                            Color = "success",
                            Icono = "bi-check2-all",
                            Nombre = "Servicio Finalizado"
                        },
                        new
                        {
                            idTipoActividadSistema = 12,
                            Activo = true,
                            Codigo = "SERVICIO_CANCELADO",
                            Color = "danger",
                            Icono = "bi-x-octagon",
                            Nombre = "Servicio Cancelado"
                        },
                        new
                        {
                            idTipoActividadSistema = 13,
                            Activo = true,
                            Codigo = "VEHICULO_ASIGNADO",
                            Color = "info",
                            Icono = "bi-truck-flatbed",
                            Nombre = "Vehículo Asignado"
                        },
                        new
                        {
                            idTipoActividadSistema = 14,
                            Activo = true,
                            Codigo = "VEHICULO_LIBERADO",
                            Color = "secondary",
                            Icono = "bi-truck",
                            Nombre = "Vehículo Liberado"
                        },
                        new
                        {
                            idTipoActividadSistema = 15,
                            Activo = true,
                            Codigo = "CONDUCTOR_ASIGNADO",
                            Color = "primary",
                            Icono = "bi-person-badge",
                            Nombre = "Conductor Asignado"
                        },
                        new
                        {
                            idTipoActividadSistema = 16,
                            Activo = true,
                            Codigo = "CONDUCTOR_LIBERADO",
                            Color = "secondary",
                            Icono = "bi-person-dash",
                            Nombre = "Conductor Liberado"
                        },
                        new
                        {
                            idTipoActividadSistema = 17,
                            Activo = true,
                            Codigo = "USUARIO_CREADO",
                            Color = "success",
                            Icono = "bi-person-plus",
                            Nombre = "Usuario Creado"
                        },
                        new
                        {
                            idTipoActividadSistema = 18,
                            Activo = true,
                            Codigo = "USUARIO_ACTUALIZADO",
                            Color = "warning",
                            Icono = "bi-person-gear",
                            Nombre = "Usuario Actualizado"
                        },
                        new
                        {
                            idTipoActividadSistema = 19,
                            Activo = true,
                            Codigo = "USUARIO_DESACTIVADO",
                            Color = "danger",
                            Icono = "bi-person-x",
                            Nombre = "Usuario Desactivado"
                        },
                        new
                        {
                            idTipoActividadSistema = 20,
                            Activo = true,
                            Codigo = "LOGIN",
                            Color = "success",
                            Icono = "bi-box-arrow-in-right",
                            Nombre = "Inicio de Sesión"
                        },
                        new
                        {
                            idTipoActividadSistema = 21,
                            Activo = true,
                            Codigo = "LOGOUT",
                            Color = "secondary",
                            Icono = "bi-box-arrow-right",
                            Nombre = "Cierre de Sesión"
                        },
                        new
                        {
                            idTipoActividadSistema = 22,
                            Activo = true,
                            Codigo = "DOCUMENTO_SUBIDO",
                            Color = "primary",
                            Icono = "bi-upload",
                            Nombre = "Documento Subido"
                        },
                        new
                        {
                            idTipoActividadSistema = 23,
                            Activo = true,
                            Codigo = "PDF_GENERADO",
                            Color = "danger",
                            Icono = "bi-file-earmark-pdf",
                            Nombre = "PDF Generado"
                        },
                        new
                        {
                            idTipoActividadSistema = 24,
                            Activo = true,
                            Codigo = "WHATSAPP_ENVIADO",
                            Color = "success",
                            Icono = "bi-whatsapp",
                            Nombre = "WhatsApp Enviado"
                        },
                        new
                        {
                            idTipoActividadSistema = 25,
                            Activo = true,
                            Codigo = "EMAIL_ENVIADO",
                            Color = "info",
                            Icono = "bi-envelope",
                            Nombre = "Correo Enviado"
                        });
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ValidacionVehiculo", b =>
                {
                    b.Property<int>("idValidacionVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idValidacionVehiculo"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaValidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LicenciaConductorVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SOATVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SeguroVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TecnoVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("idServicio")
                        .HasColumnType("int");

                    b.Property<int>("idVehiculo")
                        .HasColumnType("int");

                    b.HasKey("idValidacionVehiculo");

                    b.HasIndex("idVehiculo");

                    b.ToTable("ValidacionesVehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Vehiculos", b =>
                {
                    b.Property<int>("idVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("CapacidadCarga")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaVencimientoSOAT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoSeguro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimientoTecnoMecanica")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("PropietarioCedula")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PropietarioNombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PropietarioTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Propietariocorreo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaSOAT")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaSeguro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaTecnoMecanica")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TarifaExterna")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idVehiculo");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ActividadSistema", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.TipoActividadSistema", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("idTipoActividadSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario");

                    b.Navigation("TipoActividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizaciones", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Clientes", "Cliente")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("idUsuarioAprobador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("idUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioAprobador");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.HistRefreshToken", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "idUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("idUsuarioNavigationidUsuario");

                    b.Navigation("idUsuarioNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.LogSistema", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Permisos", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Procesos", "proceso")
                        .WithMany("Permisos")
                        .HasForeignKey("idProceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.Roles", "rol")
                        .WithMany("Permisos")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("proceso");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Procesos", "idProcesoPadreNavigation")
                        .WithMany("inverseidProcesoPadreNavigation")
                        .HasForeignKey("idProcesoPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("idProcesoPadreNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.RolesUsuarios", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Roles", "Rol")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "Usuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Servicios", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Conductores", "Conductor")
                        .WithMany("Servicios")
                        .HasForeignKey("idConductor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.Cotizaciones", "Cotizacion")
                        .WithOne("Servicio")
                        .HasForeignKey("AppServiceAndTravel.Models.Servicios", "idCotizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServiceAndTravel.Models.ProveedoresExternos", "ProveedorExterno")
                        .WithMany()
                        .HasForeignKey("idProveedorExterno")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppServiceAndTravel.Models.ApplicationUser", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("idUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppServiceAndTravel.Models.Vehiculos", "Vehiculo")
                        .WithMany("Servicios")
                        .HasForeignKey("idVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Cotizacion");

                    b.Navigation("ProveedorExterno");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ValidacionVehiculo", b =>
                {
                    b.HasOne("AppServiceAndTravel.Models.Vehiculos", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("idVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.ApplicationUser", b =>
                {
                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Clientes", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Conductores", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Cotizaciones", b =>
                {
                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Procesos", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("inverseidProcesoPadreNavigation");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Roles", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("AppServiceAndTravel.Models.Vehiculos", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
